/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, ClientDebt, Order, CajaStatus, StoreInfo } from './types';

export const INITIAL_STORES: StoreInfo[] = [
  { id: "store-01", name: "AT&T", order: 1, active: true },
  { id: "store-02", name: "Bagels & Sushi", order: 2, active: true },
  { id: "store-03", name: "Banamex", order: 3, active: true },
  { id: "store-04", name: "Bizzarro", order: 4, active: true },
  { id: "store-05", name: "Bombilla", order: 5, active: true },
  { id: "store-06", name: "Carnitas Esteban", order: 6, active: true },
  { id: "store-07", name: "Casino", order: 7, active: true },
  { id: "store-08", name: "Churrería Porfirio", order: 8, active: true },
  { id: "store-09", name: "Cinépolis", order: 9, active: true },
  { id: "store-10", name: "Coqueta & Audaz", order: 10, active: true },
  { id: "store-11", name: "Dolphy", order: 11, active: true },
  { id: "store-12", name: "Dorothy", order: 12, active: true },
  { id: "store-13", name: "Ford", order: 13, active: true },
  { id: "store-14", name: "GNC", order: 14, active: true },
  { id: "store-15", name: "Hang-Ten", order: 15, active: true },
  { id: "store-16", name: "Julio", order: 16, active: true },
  { id: "store-17", name: "KFC", order: 17, active: true },
  { id: "store-18", name: "King Bird", order: 18, active: true },
  { id: "store-19", name: "La Fe", order: 19, active: true },
  { id: "store-20", name: "Liz Minelli", order: 20, active: true },
  { id: "store-21", name: "Mama Quina", order: 21, active: true },
  { id: "store-22", name: "Martí", order: 22, active: true },
  { id: "store-23", name: "McDonald's", order: 23, active: true },
  { id: "store-24", name: "Mens Fashion", order: 24, active: true },
  { id: "store-25", name: "Mesa", order: 25, active: true },
  { id: "store-26", name: "MOBO", order: 26, active: true },
  { id: "store-27", name: "Mumuso", order: 27, active: true },
  { id: "store-28", name: "New Era", order: 28, active: true },
  { id: "store-29", name: "Nouvocell", order: 29, active: true },
  { id: "store-30", name: "Nutrisa", order: 30, active: true },
  { id: "store-31", name: "Óptica Devlyn", order: 31, active: true },
  { id: "store-32", name: "Óptica LUX", order: 32, active: true },
  { id: "store-33", name: "OXXO", order: 33, active: true },
  { id: "store-34", name: "Piccolo", order: 34, active: true },
  { id: "store-35", name: "Pizza Hut", order: 35, active: true },
  { id: "store-36", name: "Quarry", order: 36, active: true },
  { id: "store-37", name: "Santander", order: 37, active: true },
  { id: "store-38", name: "Shasa", order: 38, active: true },
  { id: "store-39", name: "Shi-Wei-Xian", order: 39, active: true },
  { id: "store-40", name: "Sportico", order: 40, active: true },
  { id: "store-41", name: "Starbucks", order: 41, active: true },
  { id: "store-42", name: "Super Naturista", order: 42, active: true },
  { id: "store-43", name: "TechHouse", order: 43, active: true },
  { id: "store-44", name: "Telcel", order: 44, active: true },
  { id: "store-45", name: "Tienda", order: 45, active: true },
  { id: "store-46", name: "Todo Moda", order: 46, active: true }
].sort((a, b) => a.name.localeCompare(b.name, "es", { sensitivity: "base" }));

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Licuado de Fresa',
    category: 'Licuados y Jugos',
    price: 45.00,
    image: '',
    active: true,
    description: 'Licuado preparado con fresas frescas seleccionadas al momento.',
    customizationOptions: ['Sin Hielo', 'Miel Extra', 'Granola'],
    variants: ['Chico (16 oz)', 'Grande (1 Litro)'],
    ingredients: ['Fresa', 'Leche', 'Azúcar']
  },
  {
    id: 'prod-02',
    name: 'Licuado de Plátano con Chocomilk',
    category: 'Licuados y Jugos',
    price: 45.00,
    image: '',
    active: true,
    description: 'Licuado cremoso de plátano con chocomilk tradicional de la casa.',
    customizationOptions: ['Sin Hielo', 'Leche de Almendra', 'Granola extra'],
    variants: ['Chico (16 oz)', 'Grande (1 Litro)'],
    ingredients: ['Plátano', 'Chocomilk', 'Leche']
  },
  {
    id: 'prod-03',
    name: 'Jugo de Naranja',
    category: 'Licuados y Jugos',
    price: 45.00,
    image: '',
    active: true,
    description: 'Jugo natural 100% exprimido del día.',
    customizationOptions: ['Sin Hielo', 'Doble Vaso'],
    variants: ['Chico (16 oz)', 'Grande (1 Litro)'],
    ingredients: ['Naranja']
  },
  {
    id: 'prod-04',
    name: 'Jugo Verde',
    category: 'Licuados y Jugos',
    price: 45.00,
    image: '',
    active: true,
    description: 'Naranja, piña, pepino, apio, espinaca y jengibre.',
    customizationOptions: ['Sin Hielo', 'Con Piña', 'Doble Espinaca'],
    variants: ['Chico (16 oz)', 'Grande (1 Litro)'],
    ingredients: ['Naranja', 'Piña', 'Pepino', 'Apio', 'Espinaca', 'Jengibre']
  },
  {
    id: 'prod-05',
    name: 'Agua Fresca',
    category: 'Licuados y Jugos',
    price: 20.00,
    image: '',
    active: true,
    description: 'Aguas frutales frescas del día preparadas en casa.',
    customizationOptions: ['Sin Hielo', 'Extra Azúcar'],
    variants: ['Chico (16 oz)', 'Grande (1 Litro)'],
    ingredients: ['Agua', 'Frutas de temporada']
  },
  {
    id: 'prod-06',
    name: 'Fruta en Vaso',
    category: 'Licuados y Jugos',
    price: 25.00,
    image: '',
    active: true,
    description: 'Fruta fresca de temporada cortada en vaso con aderezos.',
    customizationOptions: ['Tajín', 'Chamoy', 'Miguelito', 'Limón', 'Sal'],
    variants: ['Vaso Regular'],
    ingredients: ['Melón', 'Papaya', 'Plátano', 'Piña', 'Pepino']
  },
  {
    id: 'prod-07',
    name: 'Fruta en Plato',
    category: 'Licuados y Jugos',
    price: 30.00,
    image: '',
    active: true,
    description: 'Fruta fresca de temporada en plato con aderezos y complementos.',
    customizationOptions: ['Miel', 'Yogurt', 'Granola', 'Lechera'],
    variants: ['Plato Individual'],
    ingredients: ['Melón', 'Papaya', 'Plátano', 'Piña', 'Fresa']
  },
  {
    id: 'prod-08',
    name: 'Torta de Jamón',
    category: 'Comida y Snacks',
    price: 40.00,
    image: '',
    active: true,
    description: 'Bolillo crujiente caliente con jamón de pavo, jitomate y aderezos.',
    customizationOptions: ['Mayonesa', 'Lechuga', 'Jitomate', 'Queso amarillo', 'Chipotle'],
    variants: ['Sencilla', 'Doble Queso'],
    ingredients: ['Bolillo', 'Jamón de Pavo', 'Aguacate', 'Frijoles']
  },
  {
    id: 'prod-09',
    name: 'Torta Cubana',
    category: 'Comida y Snacks',
    price: 55.00,
    image: '',
    active: true,
    description: 'Deliciosa torta cubana con jamón, pierna, salchicha, de todo un poco.',
    customizationOptions: ['Mayonesa', 'Lechuga', 'Jitomate', 'Quesillo', 'Chipotle'],
    variants: ['Familiar'],
    ingredients: ['Bolillo', 'Jamón', 'Pierna', 'Salchicha', 'Quesillo']
  },
  {
    id: 'prod-10',
    name: 'Sándwich',
    category: 'Comida y Snacks',
    price: 30.00,
    image: '',
    active: true,
    description: 'Sándwich preparado al gusto en pan Sencillo o Doble.',
    customizationOptions: ['Mayonesa', 'Lechuga', 'Jitomate', 'Queso amarillo'],
    variants: ['Sencillo', 'Doble piso'],
    ingredients: ['Pan de caja', 'Jamón de Pavo', 'Queso']
  },
  {
    id: 'prod-11',
    name: 'Café de Olla',
    category: 'Otros',
    price: 15.00,
    image: '',
    active: true,
    description: 'Café de olla aromático endulzado con piloncillo y canela.',
    productLayout: 'layout_7_calientes',
    layout7Sizes: [
      { name: 'Chico', price: 15.00, active: true },
      { name: 'Mediano', price: 20.00, active: true }
    ],
    layout7AllowMilk: true,
    layout7MilkPrice: 2.00,
    layout7AllowSugar: false,
    customizationOptions: [],
    ingredients: ['Café', 'Canela', 'Piloncillo']
  },
  {
    id: 'prod-12',
    name: 'Nescafé',
    category: 'Otros',
    price: 17.00,
    image: '',
    active: true,
    description: 'Nescafé preparado caliente con leche opcional.',
    productLayout: 'layout_7_calientes',
    layout7Sizes: [
      { name: 'Chico', price: 17.00, active: true },
      { name: 'Mediano', price: 25.00, active: true }
    ],
    layout7AllowMilk: true,
    layout7MilkPrice: 3.00,
    layout7AllowSugar: true,
    customizationOptions: [],
    ingredients: ['Café soluble', 'Agua o Leche', 'Azúcar']
  },
  {
    id: 'prod-13',
    name: 'Té',
    category: 'Otros',
    price: 15.00,
    image: '',
    active: true,
    description: 'Tés calientes surtidos de hierbabuena, manzanilla, limón etc.',
    productLayout: 'layout_7_calientes',
    layout7Sizes: [
      { name: 'Chico', price: 15.00, active: true },
      { name: 'Mediano', price: 20.00, active: true }
    ],
    layout7AllowMilk: false,
    layout7MilkPrice: 0.00,
    layout7AllowSugar: true,
    customizationOptions: ['Hierbabuena', 'Manzanilla', 'Limón', 'Tila', 'Jengibre con limón', 'Té verde', 'Frutal'],
    ingredients: ['Agua', 'Bolsa de té']
  },
  {
    id: 'prod-14',
    name: 'Suadero',
    category: 'Comida y Snacks',
    price: 15.00,
    image: '',
    active: true,
    description: 'Taco individual de Suadero confitado al estilo tradicional.',
    customizationOptions: ['Con Cebolla', 'Con Cilantro', 'Salsa Roja', 'Salsa Verde'],
    variants: ['Con copia', 'Sencillo'],
    ingredients: ['Carne de Suadero', 'Tortilla de maíz']
  },
  {
    id: 'prod-15',
    name: 'Bistec',
    category: 'Comida y Snacks',
    price: 15.00,
    image: '',
    active: true,
    description: 'Taco individual de Bistec de res a la plancha.',
    customizationOptions: ['Con Cebolla', 'Con Cilantro', 'Salsa Roja', 'Salsa Verde'],
    variants: ['Con copia', 'Sencillo'],
    ingredients: ['Bistec de res', 'Tortilla de maíz']
  },
  {
    id: 'prod-16',
    name: 'Chorizo',
    category: 'Comida y Snacks',
    price: 15.00,
    image: '',
    active: true,
    description: 'Taco individual de Chorizo especiado a la plancha.',
    customizationOptions: ['Con Cebolla', 'Con Cilantro', 'Salsa Roja', 'Salsa Verde'],
    variants: ['Con copia', 'Sencillo'],
    ingredients: ['Chorizo de cerdo', 'Tortilla de maíz']
  },
  {
    id: 'prod-17',
    name: 'Mole de Pollo',
    category: 'Comida y Snacks',
    price: 40.00,
    image: '',
    active: true,
    description: 'Tacos de Mole de Pollo con arroz veracruzano de la casa.',
    customizationOptions: ['Con Arroz', 'Extra Ajónjoli'],
    variants: ['Orden 3 piezas', 'Pieza extra'],
    ingredients: ['Pollo deshebrado', 'Mole poblano', 'Tortilla']
  },
  {
    id: 'prod-18',
    name: 'Tacos Especiales ($45)',
    category: 'Comida y Snacks',
    price: 45.00,
    image: '',
    active: true,
    description: 'Orden de 3 tacos medianos de Suadero, Bistec o Chorizo.',
    customizationOptions: ['Con Todo', 'Sin Cebolla', 'Salsa aparte'],
    variants: ['Orden de 3'],
    ingredients: ['Suadero', 'Bistec', 'Chorizo', 'Tortillas']
  },
  {
    id: 'prod-19',
    name: 'Tacos de Guisado',
    category: 'Comida y Snacks',
    price: 40.00,
    image: '',
    active: true,
    description: 'Por 3 piezas se cobra $40, por 6 piezas $80, consecutivamente. Pieza extra redondeada a múltiplo de 5.',
    customizationOptions: ['Chicharrón prensa', 'Huevo con jamón', 'Salchicha mexicana', 'Chorizo con papa'],
    variants: ['Orden de 3', 'Orden de 6'],
    ingredients: ['Guisados del día', 'Tortilla de maíz']
  },
  {
    id: 'prod-20',
    name: 'Huevos al Gusto',
    category: 'Comida y Snacks',
    price: 65.00,
    image: '',
    active: true,
    description: 'Dos huevos servidos con frijol y 6 tortillas. Adiciona tortillas.',
    customizationOptions: ['A la mexicana', 'Con Jamón', 'Con Salchicha', 'Estrellados'],
    variants: ['Sencillo'],
    ingredients: ['Huevos', 'Frijoles refritos', '6 Tortillas']
  },
  {
    id: 'prod-21',
    name: 'Platillo',
    category: 'Comida y Snacks',
    price: 80.00,
    image: '',
    active: true,
    description: 'Gisados de la casa. Incluye arroz, frijol y 6 tortillas de mano.',
    customizationOptions: ['Con Mole de Pollo', 'Con Chicharrón verde', 'Huevo con jamón'],
    variants: ['Standard'],
    ingredients: ['Mero del guisado', 'Arroz', 'Frijol', '6 Tortillas']
  },
  {
    id: 'prod-22',
    name: 'Tacos Dorados',
    category: 'Comida y Snacks',
    price: 45.00,
    image: '',
    active: true,
    description: 'Orden de tacos dorados crujientes de pollo o papa.',
    customizationOptions: ['De Pollo', 'De Papa', 'Con Crema y Queso', 'Salsa roja', 'Lechuga'],
    variants: ['Orden de 3'],
    ingredients: ['Pollo o Papa', 'Tortilla frita', 'Queso y Crema']
  },
  {
    id: 'prod-23',
    name: 'Quesadillas de Papa',
    category: 'Comida y Snacks',
    price: 45.00,
    image: '',
    active: true,
    description: 'Deliciosas quesadillas de papa doraditas.',
    customizationOptions: ['Con Crema y Queso', 'Salsa verde', 'Lechuga'],
    variants: ['Orden de 3'],
    ingredients: ['Papa', 'Tortilla doblada frita']
  },
  {
    id: 'prod-24',
    name: 'Pescadillas',
    category: 'Comida y Snacks',
    price: 45.00,
    image: '',
    active: true,
    description: 'Ricas pescadillas fritas al estilo costero.',
    customizationOptions: ['Chile picado', 'Salsa', 'Limón'],
    variants: ['Orden de 3'],
    ingredients: ['Guisado de pescado', 'Tortilla frita']
  },
  {
    id: 'prod-25',
    name: 'Tostadas',
    category: 'Comida y Snacks',
    price: 45.00,
    image: '',
    active: true,
    description: 'Tostadas crujientes con pollo, papa o chorizo.',
    customizationOptions: ['De Pollo', 'De Papa', 'De Chorizo', 'Con Crema', 'Salsa'],
    variants: ['Orden de 3'],
    ingredients: ['Tostada deshidratada', 'Frijoles', 'Crema', 'Queso']
  },
  {
    id: 'prod-26',
    name: 'Picaditas',
    category: 'Comida y Snacks',
    price: 40.00,
    image: '',
    active: true,
    description: 'Pellizcadas veracruzanas con salsa de tu elección y crema.',
    customizationOptions: ['Salsa Roja', 'Salsa Verde', 'Con Cebolla', 'Sin Cebolla'],
    variants: ['Sencilla'],
    ingredients: ['Masa de maíz pellizcada', 'Salsa', 'Queso', 'Cebolla']
  },
  {
    id: 'prod-27',
    name: 'Huaraches',
    category: 'Comida y Snacks',
    price: 55.00,
    image: '',
    active: true,
    description: 'Base de maíz con frijoles, queso, crema y carne arriba.',
    customizationOptions: ['Suadero', 'Bistec', 'Chorizo', 'Salsa Verde', 'Salsa Roja'],
    variants: ['Giga Huarache'],
    ingredients: ['Masa de maíz alargada', 'Frijoles', 'Carne', 'Crema', 'Queso']
  },
  {
    id: 'prod-28',
    name: 'Enchiladas',
    category: 'Comida y Snacks',
    price: 40.00,
    image: '',
    active: true,
    description: 'Enchiladas Suizas ($45), Guajillo o Verdes ($40) al gusto.',
    customizationOptions: ['Suizas (+ $5)', 'Salsa Guajillo', 'Salsa Verde', 'Con Pollo'],
    variants: ['Orden de 3'],
    ingredients: ['Tortillas', 'Pollo', 'Salsa', 'Queso gratinado']
  },
  {
    id: 'prod-29',
    name: 'Sabritas Originales',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Bolsa de papas fritas Sabritas clásicas con salsa opcional.',
    customizationOptions: ['Con Salsa y Limón', 'Sin Salsa'],
    variants: ['Bolsa Individual'],
    ingredients: ['Papas', 'Aceite', 'Sal']
  },
  {
    id: 'prod-30',
    name: 'Sabritas Adobadas',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Bolsa de Sabritas crujientes sabor adobo.',
    customizationOptions: ['Con Salsa y Limón', 'Sin Salsa'],
    variants: ['Bolsa Individual'],
    ingredients: ['Papas adobo', 'Sal']
  },
  {
    id: 'prod-31',
    name: 'Ruffles de Queso',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Ruffles ondulados sabor queso intenso.',
    customizationOptions: ['Salsa y Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Papas fritas onduladas', 'Sabor queso']
  },
  {
    id: 'prod-32',
    name: 'Doritos Nacho',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Totopos Doritos sabor queso Nacho clásico.',
    customizationOptions: ['Salsa y Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Totopo de maíz fritado', 'Sabor queso nacho']
  },
  {
    id: 'prod-33',
    name: 'Cheetos Torciditos',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Botana de queso Cheetos Torciditos.',
    customizationOptions: ['Salsa', 'Salsa y Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Cereal de maíz extruido', 'Sabor queso']
  },
  {
    id: 'prod-34',
    name: 'Takis Fuego',
    category: 'Sabritas y Galletas',
    price: 22.00,
    image: '',
    active: true,
    description: 'Takis sabor chile y limón extremo.',
    customizationOptions: ['Salsa extra', 'Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Totopo de maíz enrollado frito', 'Sabor chile y limón']
  },
  {
    id: 'prod-35',
    name: 'Cacahuates Japoneses',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Bolsa individual de cacahuates estilo japonés.',
    customizationOptions: ['Salsa', 'Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Cacahuates', 'Soya', 'Capa de trigo tostada']
  },
  {
    id: 'prod-36',
    name: 'Cacahuates Enchilados',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Peanuts cubiertos con sazonador de chile salado.',
    customizationOptions: ['Limón'],
    variants: ['Bolsa Individual'],
    ingredients: ['Cacahuates', 'Sazonador chile y sal']
  },
  {
    id: 'prod-37',
    name: 'Galletas Chokis',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Deliciosas galletas con chispas de auténtico chocolate.',
    customizationOptions: [],
    variants: ['Paquete de galletas'],
    ingredients: ['Harina', 'Azúcar', 'Chispas de chocolate']
  },
  {
    id: 'prod-38',
    name: 'Galletas Oreo',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Galletas de sándwich rellenas de crema dulce.',
    customizationOptions: [],
    variants: ['Paquete de galletas'],
    ingredients: ['Galleta de chocolate', 'Crema de vainilla']
  },
  {
    id: 'prod-39',
    name: 'Galletas Emperador Chocolate',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Galletas Gamesa Emperador chocolate de chocolate.',
    customizationOptions: [],
    variants: ['Paquete de galletas'],
    ingredients: ['Sándwich de galleta', 'Crema de chocolate']
  },
  {
    id: 'prod-40',
    name: 'Galletas Emperador Limón',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Galletas sándwich Gamesa Emperador sabor limón.',
    customizationOptions: [],
    variants: ['Paquete de galletas'],
    ingredients: ['Sándwich de galleta', 'Fudge de limón']
  },
  {
    id: 'prod-41',
    name: 'Panditas / Gominolas',
    category: 'Sabritas y Galletas',
    price: 18.00,
    image: '',
    active: true,
    description: 'Ositos de goma frutales deliciosos.',
    customizationOptions: [],
    variants: ['Bolsa Individual'],
    ingredients: ['Azúcar', 'Goma de fécula', 'Saborizantes artificiales']
  }
];

export const INITIAL_CLIENTS: ClientDebt[] = [];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_CAJA: CajaStatus = {
  ventasDelDia: 0.00,
  pedidosPagados: 0,
  pedidosPendientes: 0,
  dineroEntregadoALider: 0.00,
  entregasPendientesALider: [],
  fondoCaja: 0.00,
  historialCierres: []
};
