-- ============================================================
-- Migración: 20260715130000_seed_sucursales_clientes.sql
-- Descripción: Insertar sucursales predefinidas
-- ============================================================

INSERT INTO public.sucursales (id, nombre, orden, active) VALUES
  ('store_att', 'AT&T', 10, true),
  ('store_bagels_sushi', 'Bagels & Sushi', 20, true),
  ('store_banamex', 'Banamex', 30, true),
  ('store_bizzarro', 'Bizzarro', 40, true),
  ('store_bombilla', 'Bombilla', 50, true),
  ('store_carnitas_esteban', 'Carnitas Esteban', 60, true),
  ('store_casino', 'Casino', 70, true),
  ('store_churreria_porfirio', 'Churrería Porfirio', 80, true),
  ('store_cinepolis', 'Cinépolis', 90, true),
  ('store_coqueta_audaz', 'Coqueta & Audaz', 100, true),
  ('store_dolphy', 'Dolphy', 110, true),
  ('store_dorothy', 'Dorothy', 120, true),
  ('store_ford', 'Ford', 130, true),
  ('store_gnc', 'GNC', 140, true),
  ('store_hang_ten', 'Hang-Ten', 150, true),
  ('store_julio', 'Julio', 160, true),
  ('store_kfc', 'KFC', 170, true),
  ('store_kia', 'Kia', 180, true),
  ('store_king_bird', 'King Bird', 190, true),
  ('store_la_fe', 'La Fe', 200, true),
  ('store_liverpool', 'Liverpool', 210, true),
  ('store_liz_minelli', 'Liz Minelli', 220, true),
  ('store_mama_quina', 'Mama Quina', 230, true),
  ('store_marti', 'Martí', 240, true),
  ('store_mcdonalds', 'McDonald''s', 250, true),
  ('store_mens_fashion', 'Men''s Fashion', 260, true),
  ('store_mesa', 'Mesa', 270, true),
  ('store_mobo', 'MOBO', 280, true),
  ('store_mumuso', 'Mumuso', 290, true),
  ('store_new_era', 'New Era', 300, true),
  ('store_nouvocell', 'Nouvocell', 310, true),
  ('store_nutrisa', 'Nutrisa', 320, true),
  ('store_optica_devlyn', 'Óptica Devlyn', 330, true),
  ('store_optica_lux', 'Óptica LUX', 340, true),
  ('store_oxxo', 'OXXO', 350, true),
  ('store_piccolo', 'Piccolo', 360, true),
  ('store_pizza_hut', 'Pizza Hut', 370, true),
  ('store_quarry', 'Quarry', 380, true),
  ('store_santander', 'Santander', 390, true),
  ('store_shasa', 'Shasa', 400, true),
  ('store_shi_wei_xian', 'Shi-Wei-Xian', 410, true),
  ('store_sportico', 'Sportico', 420, true),
  ('store_starbucks', 'Starbucks', 430, true),
  ('store_super_naturista', 'Super Naturista', 440, true),
  ('store_techhouse', 'TechHouse', 450, true),
  ('store_telcel', 'Telcel', 460, true),
  ('store_tienda', 'Tienda', 470, true),
  ('store_todo_moda', 'Todo Moda', 480, true)
ON CONFLICT (id) DO UPDATE SET 
  nombre = EXCLUDED.nombre;
